# Generated by Django 6.0.8 on 2026-10-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('reporting_year', models.PositiveIntegerField(help_text='Reporting year; does not establish activity dates or completion status.')),
                ('extension_leader', models.CharField(max_length=255)),
                ('faculty_members', models.TextField(blank=True, help_text='One name per line; participant category as reported for this record.')),
                ('lecturers', models.TextField(blank=True)),
                ('staff', models.TextField(blank=True)),
                ('research_assistants', models.TextField(blank=True)),
                ('students', models.TextField(blank=True)),
                ('source_note', models.TextField(blank=True, help_text='Internal source and name-variant notes; not published.')),
            ],
            options={
                'ordering': ['-reporting_year', 'sort_order', 'title'],
            },
        ),
    ]
