# Generated by Django 6.0.3 on 2026-03-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('AACCUP', 'AACCUP'), ('AUN_QA', 'AUN QA'), ('CHED_COPC', 'CHED COPC'), ('CHED_COE', 'CHED COE')], max_length=20)),
                ('area_code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='evidence/')),
                ('last_updated', models.DateField()),
                ('is_public_placeholder', models.BooleanField(default=True)),
            ],
        ),
    ]
