# Generated by Django 6.0.8 on 2026-10-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('reporting_year', models.CharField(help_text='Reporting year or range; not project status or confirmed start/end dates.', max_length=20)),
                ('research_leader', models.CharField(max_length=255)),
                ('team_members', models.TextField(blank=True, help_text='One additional team member per line. Do not infer employment roles from project membership.')),
                ('funding', models.CharField(choices=[('INTERNAL', 'Internally funded research'), ('EXTERNAL', 'Externally funded research')], max_length=20)),
                ('source_note', models.TextField(blank=True, help_text='Internal provenance and points requiring confirmation.')),
            ],
            options={
                'ordering': ['-reporting_year', 'sort_order', 'title'],
            },
        ),
    ]
