from django.db import migrations

PROJECTS = [('gakit',
  '2026',
  'GAKIT: Geohazard Assessment and Knowledge Integration Tool',
  'Mabaning, Abdul Aziz G.',
  'INTERNAL',
  ['Metillo, Ephrime B.',
   'Enteria, Napoleon A.',
   'Albiento, Elizabeth Edan M.',
   'Villanueva, Jomari Francis B.',
   'Castor, Paul Rodolf P.']),
 ('zcharmc',
  '2026-2027',
  'ZCharMC: Sequential Self-Supporting Zeolite-Activated Biochar Composite CO2 Capture and Conversion '
  'through Fluidized-bed Mineral Carbonation',
  'Ralf Ruffel M. Abarca',
  'EXTERNAL',
  ['Alexander 0. Mosqueda',
   'Rodel D. Guerrero',
   'Catherine 0. Acibar',
   'Paul Rodolf P. Castor',
   'Ruben L. Menchavez',
   'Francis Kirby B. Burnea',
   'Arnel D. Zamayla',
   'Vannie Joy T Resabal',
   'Apple Rose B. Alce',
   'Stephen C. Fajardo']),
 ('smart-g-id',
  '2026',
  'Smart G-ID: Design and Development of a Goat Profiling and Trading System for Direct Farmer-to-Consumer '
  'Online Transactions',
  'Ernesto E. Empig',
  'INTERNAL',
  ['Paul Rodolf P. Castor',
   'Allan P. Bicada',
   'Juffil B. Papolonias',
   'Adrian P. Galido',
   'Excel Van O. Jondonero',
   'Phoebe Ruth Alithea B. Sudaria',
   'Jomari Francis B. Villanueva',
   'Venus R. Parmisana']),
 ('aphids-detection',
  '2026',
  'Development of an IoT System for Aphids Damage Detection in Bell Pepper (Capsicum annuum) Farms of '
  'Northern Mindanao',
  'Paul Rodolf P. Castor',
  'INTERNAL',
  ['Ernesto E. Empig',
   'Jofel A. Batutay',
   'Cendy Lou O. Odvina',
   'Jomari Francis B. Villanueva',
   'Excel Van O. Jondonero',
   'Juffil B. Papolonias',
   'Eddie P. Mondejar',
   'Antonio S. Marajas',
   'Slamet Riyadi']),
 ('sign-language-translation',
  '2025',
  'Development of a Two-way and Real-time Sign Language into Voice Speech and Voice Speech into Sign '
  'Language Translation System for the Deaf and Non-deaf Community',
  'Paul Rodolf P. Castor',
  'INTERNAL',
  ['Leah A. Alindayo',
   'Jofel A. Batutay',
   'Cendy Lou O. Odvina',
   'Maria Fe P. Bahinting',
   'Excel Van O. Jondonero',
   'Juffil B. Papolonias']),
 ('liquid-vending',
  '2025',
  'Development of Liquid Vending Machine with Variable Concentration Control and Integrated Coin and Digital '
  'Payment',
  'Paul Rodolf P. Castor',
  'INTERNAL',
  ['Leah A. Alindayo', 'Jofel A. Batutay', 'Maria Fe P. Bahinting', 'Juffil B. Papolonias']),
 ('rfid-laboratory-equipment',
  '2025',
  'Development of an RFID System for Monitoring Laboratory Equipment',
  'Jomari Francis B. Villanueva',
  'INTERNAL',
  ['Paul Rodolf P. Castor',
   'Jofel A. Batutay',
   'Kristian Kirk L. Origenes',
   'Juffil B. Papolonias',
   'Excel Van O. Jondonero',
   'Junil P. Rarugal']),
 ('municipal-website-accessibility',
  '2024',
  'Accessibility Evaluation of Websites: The Case of Municipalities in Northern Mindanao',
  'Paul B. Bokingkito, Jr.',
  'INTERNAL',
  ['Apple Rose B. Alce', 'Jerame B. Beloy', 'Jerina Jean M. Ecleo', 'Adrian P. Galido']),
 ('my-boardhub',
  '2024',
  'my.BoardHub: A Smart Boarding House Management Information System',
  'Apple Rose B. Alce',
  'INTERNAL',
  ['Maria Fe P. Bahinting',
   'Jomari Francis B. Villanueva',
   'Leah A. Alindayo',
   'Paul Rodolf P. Castor',
   'Stefany Mae V. Caparida',
   'Excel Van O. Jondonero',
   'Antonio S. Marajas',
   'Ernesto E. Empig',
   'Joel I. Miano']),
 ('asean-digital-transformation',
  '2023',
  'Explorative scoping review on Digital Transformation in the Public Sector and doing business in the ASEAN',
  'Adrian P. Galido',
  'INTERNAL',
  ['Apple Rose B. Alce', 'Jerina Jean M. Ecleo']),
 ('reversed-vending',
  '2023',
  'Development of a Reversed Vending Machine with Integrated Rewards System for Campus Waste Management '
  'Application',
  'Apple Rose B. Alce',
  'INTERNAL',
  ['Antonio S. Marajas',
   'Paul Rodolf P. Castor',
   'Adrian P. Galido',
   'Stefany Mae V. Caparida',
   'Paul B. Bokingkito, Jr.']),
 ('weapon-surveillance',
  '2023',
  'Smart Campus Weapon Surveillance System Using Yolo V4',
  'Joel I. Miano',
  'INTERNAL',
  ['Apple Rose B. Alce', 'Maria Fe P. Bahinting', 'Michael A. Nabua']),
 ('smart-campus-survey',
  '2022',
  'An empirical survey of smart campus’ definitions, framework and implementation',
  'Apple Rose B. Alce',
  'INTERNAL',
  ['Jerame B. Beloy', 'Jerina Jean M. Ecleo', 'Paul B. Bokingkito, Jr.', 'Arlene B. Gil']),
 ('rice-irrigation-monitoring',
  '2022-2023',
  'Design and Development of a Microcontroller-based Water Level and Soil Moisture Monitoring and an '
  'Irrigation Scheduling System for Rice Farming',
  'Apple Rose B. Alce',
  'INTERNAL',
  ['Adrian P. Galido', 'Michael A. Nabua']),
 ('emerging-technology-prototypes',
  '2022',
  'Design and Development of System Prototypes: Addressing Local and National Problems in the context of '
  'Emerging Technologies',
  'Joel I. Miano',
  'INTERNAL',
  ['Maria Fe P. Bahinting', 'Apple Rose B. Alce', 'Michael A. Nabua'])]


def add_department_projects(apps, schema_editor):
    Project = apps.get_model("research", "ResearchProject")
    for order, (slug, year, title, leader, funding, members) in enumerate(PROJECTS):
        Project.objects.using(schema_editor.connection.alias).get_or_create(slug=slug, defaults={
            "title": title, "reporting_year": year, "research_leader": leader,
            "funding": funding, "team_members": "\n".join(dict.fromkeys(members)),
            "is_published": True, "sort_order": order,
            "source_note": "Department owner supplied reporting table, 6 October 2026. Shifted continuation rows grouped under their preceding project. Employment-role assignments are not inferred. Reporting years do not establish project status. Duplicate member entry removed from the prototypes project; other supplied spellings preserved.",
        })


class Migration(migrations.Migration):
    dependencies = [("research", "0001_initial")]
    operations = [migrations.RunPython(add_department_projects, migrations.RunPython.noop)]
