# Generated by Django 6.0.8 on 2026-10-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_department_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('authors', models.TextField(help_text='Authors in the supplied order; includes faculty, students and collaborators.')),
                ('conference', models.CharField(max_length=500)),
                ('date_label', models.CharField(max_length=100)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('withdrawn', models.BooleanField(default=False, help_text='Explicit withdrawal recorded in the department source.')),
                ('source_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', '-starts_on', 'sort_order', 'title'],
            },
        ),
    ]
