from django.db import migrations

RECORDS = [{'slug': 'conference-6399ae29113af132',
  'title': 'Integrated Machine Connectivity and High-Frequency Spindle Current Acquisition for CNC '
           'Command-Guided Process Segmentation toward Tool Wear Prediction',
  'year': 2026,
  'authors': 'Paul Rodolf P. Castor, Princess April E. Castillo, Kyle C. Macogay, Janna S. Paciteng, '
             'Hsiao-Yeh Chu',
  'conference': 'International Conference on Engineering Tribology and Applied Technology 2026 (ICETAT2026)',
  'date_label': 'November 6-8, 2026',
  'starts_on': '2026-11-06',
  'ends_on': '2026-11-08',
  'location': 'Tainan, Taiwan',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-97fdb55fcb52fc96',
  'title': 'VermiSense: A Smart Vermicomposting System with Monitoring and Notifications for Enhanced '
           'African Night Crawler Compost Bin',
  'year': 2026,
  'authors': 'Junie Jebreel M. Botawan II, Jarmaine Mesbahoddin M. Abdul, Binyusoph P. Sansarona, Juffil B. '
             'Papolonias, Ernesto E. Empig',
  'conference': 'Regional Conference on Information Technology Education (RCITE) 2026',
  'date_label': 'September 17–18, 2026',
  'starts_on': '2026-09-17',
  'ends_on': '2026-09-18',
  'location': 'Iligan City, Philippines',
  'scope': 'REGIONAL',
  'withdrawn': False},
 {'slug': 'conference-7e85422aa48dce3b',
  'title': 'VermiSense: A Smart Vermicomposting System with Monitoring and Notifications for Enhanced '
           'African Night Crawler Compost Bin',
  'year': 2026,
  'authors': 'Junie Jebreel M. Botawan II, Jarmaine Mesbahoddin M. Abdul, Binyusoph P. Sansarona, Juffil B. '
             'Papolonias, Ernesto E. Empig',
  'conference': 'ICUNSSI 2026: The 2nd International Conference on UN SDGs and Social Innovation',
  'date_label': 'September 24-25, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-25',
  'location': 'Iligan City, Philippines',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-3014ac8f990de334',
  'title': 'A Unified Deep Learning Pipeline for Photoquadrat Localization and Per-Cell Seagrass Coverage '
           'Classification',
  'year': 2026,
  'authors': 'Shiela Mae Barro, Cherry Mae Villame, Leah Alindayo, Maria Fe Bahinting, Angel Lyn Mirayo, '
             'Aileen Narvaez',
  'conference': 'ICCAS 2026: 26th International Conference on Control, Automation, and Systems',
  'date_label': 'October 27-30, 2026',
  'starts_on': '2026-10-27',
  'ends_on': '2026-10-30',
  'location': 'Sapporo, Japan',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-49b8f3e1566f5eda',
  'title': 'SmarTax: An Automated Insect Digitization System Integrating AI-Based Identification and '
           'Interactive 3D Visualization of Selected Coleoptera',
  'year': 2026,
  'authors': 'Renemy Sator, Cherry Mae Villame, Leah Alindayo, Eddie Mondejar',
  'conference': 'ICCAS 2026: 26th International Conference on Control, Automation, and Systems',
  'date_label': 'October 27-30, 2026',
  'starts_on': '2026-10-27',
  'ends_on': '2026-10-30',
  'location': 'Sapporo, Japan',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-a07fbbfb19a280b5',
  'title': 'Computational Approaches, Evidence Maturity, and Research Gaps in Bell-Pepper Disease and Pest '
           'Monitoring: A Systematic Literature Review',
  'year': 2026,
  'authors': 'Tristan Listanco, Phoebien Cañete, Shanice Reih Tanque, Apple Rose Alce, Paul Rodolf Castor',
  'conference': 'The 17th International Conference on Emerging Ubiquitous Systems and Pervasive Networks '
                '(EUSPN)',
  'date_label': 'October 28-30, 2026',
  'starts_on': '2026-10-28',
  'ends_on': '2026-10-30',
  'location': 'Almaty, Kazakhstan',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-9254b886cea520a3',
  'title': 'Design and Development of a MobileNetV3-Based Rice Tungro Disease Detection Model for Raspberry '
           'Pi 5 Edge',
  'year': 2026,
  'authors': 'Crischan Larita, Paul Rodolf Castor, Apple Rose Alce, Harreez Villaruz',
  'conference': 'The 17th International Conference on Emerging Ubiquitous Systems and Pervasive Networks '
                '(EUSPN)',
  'date_label': 'October 28-30, 2026',
  'starts_on': '2026-10-28',
  'ends_on': '2026-10-30',
  'location': 'Almaty, Kazakhstan',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-30e3c76118a36dbd',
  'title': 'AvianTech: An Edge-AI IoT Architecture for Real-Time Multimodal Visual-Acoustic Avian '
           'Biodiversity Monitoring',
  'year': 2026,
  'authors': 'Alyssa Usman, Adrian Galido, Jyresa Mae Amboang, Apple Rose Alce',
  'conference': 'The 17th International Conference on Emerging Ubiquitous Systems and Pervasive Networks '
                '(EUSPN)',
  'date_label': 'October 28-30, 2026',
  'starts_on': '2026-10-28',
  'ends_on': '2026-10-30',
  'location': 'Almaty, Kazakhstan',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-c2a2e39ba27ad697',
  'title': 'Embedded IoT-Based Real-Time Room-Level Energy Monitoring, Load Control and Automated Billing '
           'System',
  'year': 2026,
  'authors': 'Apple Rose B. Alce, Mohana Shanmugam, Prinnie Boy D. Torregoza, Darlene Krissa G. Zapatos, '
             'Jevon Karl A. Tuba, Paul Rodolf P. Castor, Halimah Badioze Zaman',
  'conference': '2026 IEEE International Conference on Computing (ICOCO)',
  'date_label': 'October 12-14, 2026',
  'starts_on': '2026-10-12',
  'ends_on': '2026-10-14',
  'location': 'Hotel Kuah, Langkawi, Kedah, Malaysia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-2c1762ebd90aaa2e',
  'title': 'Geo-Goat: Evaluation of a LoRaWAN-Enabled Geofencing Collar for Smallholder Goat Monitoring',
  'year': 2026,
  'authors': 'Michael Jibrell J. Escolano, Israfeel Mikhail A. Tagorda, Yke Cedrick C. Tenecio, Apple Rose '
             'B. Alce, and Paul Rodolf P. Castor',
  'conference': '2026 13th International Conference on Electrical Engineering, Computer Science and '
                'Informatics (EECSI)',
  'date_label': 'September 2-3. 2026',
  'starts_on': '2026-09-02',
  'ends_on': '2026-09-03',
  'location': 'Yogyakarta, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-8f11f6d9944fa04b',
  'title': 'Design and Development of a YOLO-Based Water Level Monitoring System on NVIDIA Jetson Orin Nano',
  'year': 2026,
  'authors': 'Mary Ann Gliefen Bermudo, Apple Rose Alce, Adrian Galido',
  'conference': '2026 International Conference on Information Technology and Computing (ICITCOM)',
  'date_label': 'August 5, 2026',
  'starts_on': '2026-08-05',
  'ends_on': '2026-08-05',
  'location': 'Universitas Muhammadiyah Yogyakarta, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-f01a68a19dcf0aa6',
  'title': 'SWiPS: Edge AI Pedestrian Detection and Visual Advisory for Unsignalized Campus Crosswalks Using '
           'YOLOv8n',
  'year': 2026,
  'authors': 'Jyresa Mae M. Amboang, Adrian Galido and Apple Rose B. Alce',
  'conference': '2026 International Conference on Information Technology and Computing (ICITCOM)',
  'date_label': 'August 5, 2026',
  'starts_on': '2026-08-05',
  'ends_on': '2026-08-05',
  'location': 'Universitas Muhammadiyah Yogyakarta, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': True},
 {'slug': 'conference-0fb74f38dbef1efe',
  'title': 'TREON: Design and Development of an Edge-Based AR Smart Mirror for Real-Time Virtual Lipstick '
           'Try-On',
  'year': 2026,
  'authors': 'Sean Coen Benson, Karl Michael Bulos, Febby Ann Burlado, Jomari Francis B. Villanueva, Apple '
             'Rose B. Alce, Excel Van Jondonero, Juffil Papolonias, Stefany Mae Caparida',
  'conference': '2026 International Conference on Information Technology and Computing (ICITCOM)',
  'date_label': 'August 5, 2026',
  'starts_on': '2026-08-05',
  'ends_on': '2026-08-05',
  'location': 'Universitas Muhammadiyah Yogyakarta, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': True},
 {'slug': 'conference-c5f600dc5f8fe850',
  'title': 'IoT-Based CO₂ Monitoring for Sustainable Indoor and Outdoor Environments',
  'year': 2026,
  'authors': 'Ralf Ruffel Abarca, Edrian Abilay, Apple Rose Alce, Paul Rodolf Castor',
  'conference': 'ICUNSSI 2026: The 2nd International Conference on UN SDGs and Social Innovation',
  'date_label': 'September 24-25, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-25',
  'location': 'Iligan City, Philippines',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-bdc82d438facee77',
  'title': 'A Requirement-Driven Architecture for Smart G-ID: Design and Development of a Goat Profiling and '
           'Trading System for Direct Farmer-to-Consumer Transactions',
  'year': 2026,
  'authors': 'Princess April E. Castillo, Andrew Earl E. Andres, John Benedict D. Bernal, Ernesto E. Empig, '
             'Paul Rodolf P. Castor, Venus R. Parmisana, Adrian P. Galido and Jomari Francis B. Villanueva',
  'conference': 'ICUNSSI 2026: The 2nd International Conference on UN SDGs and Social Innovation',
  'date_label': 'September 24-25, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-25',
  'location': 'Iligan City, Philippines',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-5aae3ce6c65c2c2d',
  'title': 'Bridging Health Equity and Technology: A Portable Edge Computing System for Counterfeit Medicine '
           'Tablet Packaging Identification',
  'year': 2026,
  'authors': 'Danna Mae P. Ricafort, Maxine R. Ardiayon, Michelle N. Bacolcol , Excel Van O. Jondonero, '
             'Haron Hakeen D. Lua, Juffil B. Papolonias, Marjorie M. Tabigue, Stefany Mae V. Caparida, '
             'Phoebe Ruth Alithea B. Sudaria',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-dfecf710ef98a0ae',
  'title': 'An Intelligent Integrated Work and Financial Planning Decision Support System for Higher '
           'Education Institutions',
  'year': 2026,
  'authors': 'Reuh Deen B. Mascariñas, Moh’d Asrin A. Tabao, Apple Rose Alce',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-117ae5001c5f2588',
  'title': 'Digital Twin–Driven Urban Traffic Noise Modeling with Real-Time IoT Classification and '
           'Scenario-Based Sensitivity Analysis',
  'year': 2026,
  'authors': 'Reymark John A. Macapanas, Juffil B. Papolonias, Excel Van O. Jondonero',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-fbfb5ed2b244d3ac',
  'title': 'AI-Driven Digital Twin Framework for Urban Food Market Stability Forecasting Using Composite '
           'Stability Index and Government Price Monitoring Data',
  'year': 2026,
  'authors': 'Reymark John A. Macapanas, Juffil B. Papolonias, Excel Van O. Jondonero',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-a1dd90bb2d88fd97',
  'title': 'TREON: An Augmented Reality Smart Mirror for Virtual Lipstick Try-on',
  'year': 2026,
  'authors': 'Sean Coen V. Benson, Febby Ann C. Burlado, Karl Michael T. Bulos, Jomari Francis Villanueva, '
             'Apple Rose B. Alce, Juffil B. Papolonias, Excel Van O. Jononero, & Stefany Mae V. Caparida',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-b86d133ea4bad4f1',
  'title': 'A Systematic Review on AI-Based Detection of Rubber Tree Leaf Diseases',
  'year': 2026,
  'authors': 'Ike S. Russel, Paul Rodolf P. Castor, Orven E. Llantos',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-f2361c32ebc4852f',
  'title': 'Internet of Things and Sensor-Based Systems for Livestock Profiling: A Systematic Literature '
           'Review',
  'year': 2026,
  'authors': 'Princess April E. Castillo, Andrew Earl L. Andres, John Benedict D. Bernal, Paul Rodolf P. '
             'Castor, Venus R. Parmisana, Ernesto E. Empig',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-91a183018f997249',
  'title': 'Designing and Developing a Hyperlocal Air Quality Monitoring System for Philippine Urban '
           'Environments',
  'year': 2026,
  'authors': 'Mark Joceph A. Apao, Paul Rodolf P. Castor, Adrian P. Galido',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-726975490390643c',
  'title': 'Bridging the Tungro Gap: a Systematic Literature Review of Edge-Optimized Deep Learning for Rice '
           'Disease Detection',
  'year': 2026,
  'authors': 'Crischan A. Larita, Apple Rose B. Alce, Paul Rodolf P. Castor, Harreez M. Villaruz–Quimque',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-fd87286d05d95a7c',
  'title': 'Development and Evaluation of a Wearable Headband-Based ASL Letter Recognition Prototype: A '
           'Pilot Feasibility, Usability, and Acceptance Study',
  'year': 2026,
  'authors': 'Darel James A. Narvasa, Jehan Oswald T. Colao, Generyll Rose C. Jalbuna, Paul Rodolf P. '
             'Castor, Apple Rose B. Alce',
  'conference': '6th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2026',
  'starts_on': '2026-09-24',
  'ends_on': '2026-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-c31cecd2803282f1',
  'title': 'Bunchy Top Virus Detection from UAV Imagery Using DeepLabv3+ with MobileNetV2: A Semantic '
           'Segmentation Approach',
  'year': 2026,
  'authors': 'Repulle Jewelane, Leah A. Alindayo, Paul Rodolf Castor, Maria Fe Bahinting, Apple Rose Alce',
  'conference': '4th International Conference on Computer, Cybernetics and Education (ICCCE)',
  'date_label': 'February 27-28, 2026',
  'starts_on': '2026-02-27',
  'ends_on': '2026-02-28',
  'location': 'Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-10dd6911e0c19aa3',
  'title': 'Design and Development of an IoT-based Hybrid Seaweed Dryer Powered by Renewable Solar Energy',
  'year': 2026,
  'authors': 'Rey Christian M. Villarin , Leah A. Alindayo, Stefany Mae V. Caparida, Maria Fe Bahinting, and '
             'Cherry Mae Villame',
  'conference': '4th International Conference on Computer, Cybernetics and Education (ICCCE)',
  'date_label': 'February 27-28, 2026',
  'starts_on': '2026-02-27',
  'ends_on': '2026-02-28',
  'location': 'Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-ace967696e93ddf9',
  'title': 'Design and Development of a Landslide Monitoring loT-Based Wireless Sensor Network with Early '
           'Warning System',
  'year': 2026,
  'authors': 'Nilo Tubio II, Leah A. Alindayo, Stefany Mae V. Caparida, Maria Fe Bahinting',
  'conference': '4th International Conference on Computer, Cybernetics and Education (ICCCE)',
  'date_label': 'February 27-28, 2026',
  'starts_on': '2026-02-27',
  'ends_on': '2026-02-28',
  'location': 'Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-adaa0bf4e40eced0',
  'title': 'Development of a Reinforcement Learning-X-Plane Simulation Pipeline for Guidance and Control of '
           'Drone Smart Gliding Micromunition',
  'year': 2026,
  'authors': 'Dynah Opeso, Immanuael Paradela, Donato Juayang, Alvin Vandinas, Maria Fe Bahinting, Leah A. '
             'Alindayo, and Sherwin Guinaldo',
  'conference': '31st International Symposium on Artificial Life and Robotics and 11th International '
                'Symposium on BioComplexity',
  'date_label': 'January 21-23,2026',
  'starts_on': '2026-01-21',
  'ends_on': '2026-01-23',
  'location': 'B-Con PLAZA, Beppu, JAPAN',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-db4a86c440866e72',
  'title': 'An IoT-Based System for Real-Time Water Leak Detection with Integrated Alert Mechanism',
  'year': 2025,
  'authors': 'Mary Christylle Cincoflores, Kenn Roland Ello, Marjorie M. Tabigue, Apple Rose B. Alce, Paul '
             'Rodolf Castor, Ernesto E. Empig, Stefany Mae V. Caparida',
  'conference': 'International Conference on Information Technology Education (ICITE) 2025',
  'date_label': 'November 27-29, 2025',
  'starts_on': '2025-11-27',
  'ends_on': '2025-11-29',
  'location': 'Ho Chi Minh, Vietnam',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-99d7b792ccc4f551',
  'title': 'HawkWise: A Web Solution for Waste Collection Monitoring and its Implications for AI-Integrated '
           'IT Education in Urban Communities',
  'year': 2025,
  'authors': 'Marjorie Tabigue, Jeah Pearl Menette Daligdig, Gabrielle Lanuza, Christine Anne Pintac, Haron '
             'Hakeen Lua, Jerina Jean Ecleo, Stefany Mae Caparida, Jude Positos',
  'conference': 'International Conference on Information Technology Education (ICITE) 2025',
  'date_label': 'November 27-29, 2025',
  'starts_on': '2025-11-27',
  'ends_on': '2025-11-29',
  'location': 'Ho Chi Minh, Vietnam',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-8960e94d76473f3a',
  'title': 'My.BoardHub: Development of a Single-Board Computer-Based Security System using Artificial '
           'Intelligence of Things for Boarding Houses',
  'year': 2025,
  'authors': 'Raymond M Valdepeñas, Marie Glo C Generalao, Selena B Suario, Apple Rose B Alce, Paul Rodolf P '
             'Castor, Jomari Francis B Villanueva, Leah A Alindayo, Ernesto E Empig',
  'conference': '5th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2025',
  'starts_on': '2025-09-24',
  'ends_on': '2025-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-3bf4868ab1cbe2fb',
  'title': 'Deep Learning-Based Forecasting of Environment Noise in Campus Buildings Using Bi-LSTM and IoT '
           'Integration',
  'year': 2025,
  'authors': 'Reymark-John Macapanas, Adrian Galido, Apple Rose Alce',
  'conference': '5th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2025',
  'starts_on': '2025-09-24',
  'ends_on': '2025-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-39d09ca730dc933c',
  'title': 'Performance Analysis of YOLO-based Architecture for Water Level Monitoring',
  'year': 2025,
  'authors': 'Mary Ann Gliefen Bermudo, Adrian Galido, Apple Rose Alce',
  'conference': '5th International Conference on Novel & Intelligent Digital Systems',
  'date_label': 'September 24-26, 2025',
  'starts_on': '2025-09-24',
  'ends_on': '2025-09-26',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-29595ee1f2ddcdee',
  'title': 'BirdNET in Avian Diversity Monitoring: Capabilities and Challenges',
  'year': 2025,
  'authors': 'Alyssa M. Usman, Apple Rose B. Alce, Adrian P. Galido',
  'conference': 'The Eighth Information Systems International Conference (ISICO)',
  'date_label': 'August 4-6, 2025',
  'starts_on': '2025-08-04',
  'ends_on': '2025-08-06',
  'location': 'Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-3d0289e5266f3a4a',
  'title': 'AI-Based Disease Detection for Cacao Black Pod Rot (p. palmivora): A Scoping Review',
  'year': 2025,
  'authors': 'Neil Christian P. Balayon, Paul Rodolf P. Castor, Adrian P. Galido',
  'conference': 'The Eighth Information Systems International Conference (ISICO)',
  'date_label': 'August 4-6, 2025',
  'starts_on': '2025-08-04',
  'ends_on': '2025-08-06',
  'location': 'Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-607c768256913e01',
  'title': 'From Problem Analysis to Design Thinking: Developing the Swips System for Urban Pedestrian '
           'Safety',
  'year': 2025,
  'authors': 'Jyresa Mae M. Amboang, Apple Rose B. Alce, Adrian P. Galido',
  'conference': 'The Eighth Information Systems International Conference (ISICO)',
  'date_label': 'August 4-6, 2025',
  'starts_on': '2025-08-04',
  'ends_on': '2025-08-06',
  'location': 'Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-e355e99efd040598',
  'title': 'Smart Noise Monitoring and Forecasting in Academic Environments: An IoT-Based Evaluation with '
           'Kalman Filtering and Bi-LSTM Toward a Smart Campus',
  'year': 2025,
  'authors': 'Reymark-John Macapanas, Adrian Galido, Apple Rose Alce',
  'conference': 'The Eighth Information Systems International Conference (ISICO)',
  'date_label': 'August 4-6, 2025',
  'starts_on': '2025-08-04',
  'ends_on': '2025-08-06',
  'location': 'Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-2a0fa2306cbf10b6',
  'title': 'Prototyping a noise monitoring system for a smart campus',
  'year': 2025,
  'authors': 'Reymark-John Macapanas, Apple Rose Alce, Adrian Galido',
  'conference': '2025 AUA Asia-Pacific Public Policy Network (AP-PPN) Conference on Public Policy',
  'date_label': 'May 21-23, 2025',
  'starts_on': '2025-05-21',
  'ends_on': '2025-05-23',
  'location': 'Hong Kong (SAR)',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-108917f79a5e53cf',
  'title': 'Eyeway: An Artificial Intelligence Of Things Pothole Detection System With Map Visualization',
  'year': 2024,
  'authors': 'Leonhel V. Fortin, Arjean Rose V. Delos Santos, Pul Joven B. Cagud, Paul Rodolf Castor, Orven '
             'E. Llantos',
  'conference': 'The 15th International Conference on Emerging Ubiquitous Systems and Pervasive Networks '
                '(EUSPN 2024)',
  'date_label': 'October 28-30, 2024',
  'starts_on': '2024-10-28',
  'ends_on': '2024-10-30',
  'location': 'Leuven, Belgium',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-50d9b16f2857e4e1',
  'title': 'Development of an Image-based Reversed Vending Machine using Raspberry Pi',
  'year': 2024,
  'authors': 'Apple Rose Alce, Adrian P. Galido',
  'conference': '4th International Conference on Novel and Intelligent Digital Systems 2024',
  'date_label': 'September 25-27, 2024',
  'starts_on': '2024-09-25',
  'ends_on': '2024-09-27',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-f97d04bc14f695dc',
  'title': 'Exploring Smart City Analytical Framework Evidence from Select Case Studies',
  'year': 2023,
  'authors': 'Apple Rose B. Alce, Jerina Jean M. Ecleo, Adrian P. Galido',
  'conference': '3rd Novel & Intelligent Systems Conference in Athens',
  'date_label': 'September 28-29, 2023',
  'starts_on': '2023-09-28',
  'ends_on': '2023-09-29',
  'location': 'Athens, Greece',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-654e449f6bf2fef3',
  'title': 'Automated Safe AWD Rice Irrigation Scheduling Using Low-Power WAN Technology',
  'year': 2023,
  'authors': 'Apple Rose B. Alce, Adrian P. Galido',
  'conference': '7th Information Systems International Conference',
  'date_label': 'July 26-28, 2023',
  'starts_on': '2023-07-26',
  'ends_on': '2023-07-28',
  'location': 'Sanur in Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-643389de6a615ef3',
  'title': 'Design and Development of a University Outdoor Air Quality Monitoring System',
  'year': 2023,
  'authors': 'Paul Rodolf P. Castor, Michael A. Nabua, Paul B. Bokingkito, Jr., Apple Rose B. Alce, Adrian '
             'P. Galido',
  'conference': '7th Information Systems International Conference',
  'date_label': 'July 26-28, 2023',
  'starts_on': '2023-07-26',
  'ends_on': '2023-07-28',
  'location': 'Sanur in Bali, Indonesia',
  'scope': 'INTERNATIONAL',
  'withdrawn': False},
 {'slug': 'conference-b1be6a199db19557',
  'title': 'Development of Water and Soil Moisture Monitoring and an Irrigation Scheduling System for Rice '
           'Farming',
  'year': 2022,
  'authors': 'Apple Rose B. Alce, Adrian P. Galido, Michael A. Nabua',
  'conference': 'International Conference on Education, Environment and Agriculture (ICEEA 2022) via Zoom',
  'date_label': 'August 30-31, 2022',
  'starts_on': '2022-08-30',
  'ends_on': '2022-08-31',
  'location': 'Central Bicol State University of Agriculture',
  'scope': 'INTERNATIONAL',
  'withdrawn': False}]


def add_conference_records(apps, schema_editor):
    Record = apps.get_model("research", "ConferenceRecord")
    for order, values in enumerate(RECORDS):
        data = dict(values)
        slug = data.pop("slug")
        Record.objects.using(schema_editor.connection.alias).get_or_create(slug=slug, defaults={
            **data, "sort_order": order, "is_published": True,
            "source_note": "Department-owner supplied conference table, 6 October 2026. Listing is not confirmation of completed presentation, acceptance or publication. Two entries explicitly withdrawn. Athens, Grace corrected to Athens, Greece by owner. Whitespace and obvious Visualizationof spacing corrected; other names and titles preserved.",
        })


class Migration(migrations.Migration):
    dependencies = [("research", "0003_conferencerecord")]
    operations = [migrations.RunPython(add_conference_records, migrations.RunPython.noop)]
