# Generated by Django 6.0.8 on 2026-10-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_department_conferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(help_text='First online year where confirmed; otherwise proceedings or citation year.')),
                ('authors', models.TextField(help_text='Complete author list in publisher order, separated by semicolons.')),
                ('venue', models.TextField(help_text='Journal, proceedings or preprint repository.')),
                ('kind', models.CharField(choices=[('JOURNAL', 'Journal article'), ('PROCEEDINGS', 'Conference paper'), ('PREPRINT', 'Preprint')], max_length=20)),
                ('citation_details', models.CharField(blank=True, max_length=255)),
                ('date_label', models.CharField(help_text='Use only the precision supported by the publisher; distinguish online and citation dates.', max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('source_note', models.TextField(blank=True, help_text='Internal verification notes and provenance.')),
            ],
            options={
                'ordering': ['-year', 'sort_order', 'title'],
            },
        ),
    ]
