from django.db import migrations

RECORDS = [{'slug': 'smart-noise-monitoring-and-forecasting-in-academic-environments-an-iot-based-evaluation-with-kalman-filtering-and-bi-lstm-toward-a-smart-campus',
  'title': 'Smart noise monitoring and forecasting in academic environments: An IoT-based evaluation with '
           'Kalman filtering and Bi-LSTM toward a smart campus',
  'year': 2026,
  'authors': 'Reymark-John A. Macapanas; Adrian P. Galido; Apple Rose B. Alce',
  'venue': 'Procedia Computer Science',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 284 · Pages 287–294',
  'date_label': '2026',
  'publisher': 'Elsevier BV',
  'doi': '10.1016/j.procs.2026.07.005',
  'source_url': 'https://doi.org/10.1016/j.procs.2026.07.005',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 1. ',
  'is_published': True,
  'sort_order': 0},
 {'slug': 'birdnet-in-avian-diversity-monitoring-capabilities-and-challenges',
  'title': 'BirdNET in avian diversity monitoring: capabilities and challenges',
  'year': 2026,
  'authors': 'Alyssa M. Usman; Apple Rose B. Alce; Adrian P. Galido',
  'venue': 'Procedia Computer Science',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 284 · Pages 1215–1223',
  'date_label': '2026',
  'publisher': 'Elsevier BV',
  'doi': '10.1016/j.procs.2026.07.109',
  'source_url': 'https://doi.org/10.1016/j.procs.2026.07.109',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 2. ',
  'is_published': True,
  'sort_order': 1},
 {'slug': 'from-problem-analysis-to-design-thinking-developing-the-swips-system-for-urban-pedestrian-safety',
  'title': 'From problem analysis to design thinking: Developing the SWiPS system for urban pedestrian '
           'safety',
  'year': 2026,
  'authors': 'Jyresa Mae M. Amboang; Apple Rose B. Alce; Adrian P. Galido',
  'venue': 'Procedia Computer Science',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 284 · Pages 295–301',
  'date_label': '2026',
  'publisher': 'Elsevier BV',
  'doi': '10.1016/j.procs.2026.07.006',
  'source_url': 'https://doi.org/10.1016/j.procs.2026.07.006',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 3. ',
  'is_published': True,
  'sort_order': 2},
 {'slug': 'ai-based-disease-detection-for-cacao-black-pod-rot-p-palmivora-a-scoping-review',
  'title': 'AI-based disease detection for cacao black pod rot (p. palmivora): a scoping review',
  'year': 2026,
  'authors': 'Neil Christian P. Balayon; Paul Rodolf P. Castor; Adrian P. Galido',
  'venue': 'Procedia Computer Science',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 284 · Pages 1150–1157',
  'date_label': '2026',
  'publisher': 'Elsevier BV',
  'doi': '10.1016/j.procs.2026.07.102',
  'source_url': 'https://doi.org/10.1016/j.procs.2026.07.102',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 4. ',
  'is_published': True,
  'sort_order': 3},
 {'slug': 'robolikha-extension-program-for-inclusive-stem-and-sustainable-development',
  'title': 'RoboLikha extension program for inclusive STEM and sustainable development',
  'year': 2026,
  'authors': 'Helen Grace Gonzales; Ruvel J. Cuasito Sr.; Marjun S. Sequera; Camilo Jose S. Salvana; Troadio '
             'M. Barbosa; Dominic O. Cagadas; Romano A. Pimentel; Dexter L. Duat; Christine Marie J. Madrid; '
             'Geovani Pabilona; Rozano A. Pimentel; Justine Clarenz L. Auxilio; Jerry B. Halibas; Ellen Jane '
             'G. Gulben; Daxter William L. Gulben; Cran Leigh Mae A. Salamanca; John Huss E. Tongco; '
             'Kathleen E. Padrigalan; Maria Teresa M. Fajardo; Muslikhin Muslikhin',
  'venue': 'Jurnal Cakrawala Pendidikan',
  'kind': 'JOURNAL',
  'citation_details': 'Volume 45, issue 2',
  'date_label': 'First published online: 9 June 2026',
  'publisher': 'Universitas Negeri Yogyakarta',
  'doi': '10.21831/cp.v45i2.91105',
  'source_url': 'https://doi.org/10.21831/cp.v45i2.91105',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 5. ',
  'is_published': True,
  'sort_order': 4},
 {'slug': 'development-of-a-low-cost-lora-based-system-for-particulate-matter-2-5-data-acquisition',
  'title': 'Development of a Low-Cost LoRa-Based System for Particulate Matter 2.5 Data Acquisition',
  'year': 2026,
  'authors': 'Jomari Francis B. Villanueva; Adrian P. Galido; Apple Rose B. Alce; Paul B. Bokingkito; '
             'Alexander O. Mosqueda; Michael A. Nabua',
  'venue': '2026 International Conference on Artificial Intelligence, Computer, Data Sciences and '
           'Applications (ACDSA)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Pages 1–7',
  'date_label': '2026',
  'publisher': 'IEEE',
  'doi': '10.1109/acdsa67686.2026.11468017',
  'source_url': 'https://doi.org/10.1109/acdsa67686.2026.11468017',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 6. ',
  'is_published': True,
  'sort_order': 5},
 {'slug': 'deep-learning-based-forecasting-of-environmental-noise-in-campus-buildings-using-bi-lstm-and-iot-integration',
  'title': 'Deep Learning-Based Forecasting of Environmental Noise in Campus Buildings Using Bi-LSTM and IoT '
           'Integration',
  'year': 2026,
  'authors': 'Reymark John A. Macapanas; Apple Rose B. Alce; Adrian P. Galido',
  'venue': 'Lecture Notes in Networks and Systems · Novel and Intelligent Digital Systems: Proceedings of '
           'the 5th International Conference (NiDS 2025)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 1707 · Pages 100–111',
  'date_label': 'First published online: 2 January 2026',
  'publisher': 'Springer Nature Switzerland',
  'doi': '10.1007/978-3-032-10824-1_8',
  'source_url': 'https://doi.org/10.1007/978-3-032-10824-1_8',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 7. ',
  'is_published': True,
  'sort_order': 6},
 {'slug': 'performance-analysis-of-yolo-based-architecture-for-water-level-monitoring',
  'title': 'Performance Analysis of YOLO-Based Architecture for Water Level Monitoring',
  'year': 2026,
  'authors': 'Mary Ann Gliefen A. Bermudo; Apple Rose B. Alce; Adrian P. Galido',
  'venue': 'Lecture Notes in Networks and Systems · Novel and Intelligent Digital Systems: Proceedings of '
           'the 5th International Conference (NiDS 2025)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 1707 · Pages 361–372',
  'date_label': 'First published online: 2 January 2026',
  'publisher': 'Springer Nature Switzerland',
  'doi': '10.1007/978-3-032-10824-1_28',
  'source_url': 'https://doi.org/10.1007/978-3-032-10824-1_28',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 8. ',
  'is_published': True,
  'sort_order': 7},
 {'slug': 'my-boardhub-development-of-a-single-board-computer-based-security-system-using-artificial-intelligence-of-things-for-boarding-houses',
  'title': 'My.BoardHub: Development of a Single-Board Computer-Based Security System Using Artificial '
           'Intelligence of Things for Boarding Houses',
  'year': 2025,
  'authors': 'Raymond M. Valdepeñas; Marie Glo C. Generalao; Selena B. Suario; Apple Rose B. Alce; Paul '
             'Rodolf P. Castor; Jomari Francis B. Villanueva; Leah A. Alindayo; Ernesto E. Empig',
  'venue': 'Lecture Notes in Networks and Systems · Novel and Intelligent Digital Systems: Proceedings of '
           'the 5th International Conference (NiDS 2025)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 1644 · Pages 59–70',
  'date_label': 'First published online: 3 October 2025; proceedings citation year: 2026',
  'publisher': 'Springer Nature Switzerland',
  'doi': '10.1007/978-3-032-06634-3_6',
  'source_url': 'https://doi.org/10.1007/978-3-032-06634-3_6',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 9. ',
  'is_published': True,
  'sort_order': 8},
 {'slug': 'design-and-development-of-an-iot-based-sustainable-seaweed-drying-temperature-uniformity-36-40-c-validation-for-kappaphycus-alvarezii',
  'title': 'Design and Development of an IoT-Based Sustainable Seaweed Drying: Temperature uniformity '
           '(36-40°C) Validation for “Kappaphycus alvarezii”',
  'year': 2025,
  'authors': 'Rey Christian M. Villarin; Leah A. Alindayo; Stefany Mae V. Caparida; Maria Fe P. Bahinting; '
             'Cherry Mae J. Galangque',
  'venue': 'Journal of Information Systems Engineering and Management',
  'kind': 'JOURNAL',
  'citation_details': 'Volume 10, issue 63s · Pages 1335–1348',
  'date_label': 'First published online: 13 December 2025',
  'publisher': 'Science Research Society',
  'doi': '10.52783/jisem.v10i63s.14012',
  'source_url': 'https://doi.org/10.52783/jisem.v10i63s.14012',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 10. Full author list from publisher page; Crossref deposit is '
                 'incomplete.',
  'is_published': True,
  'sort_order': 9},
 {'slug': 'development-of-water-quality-monitoring-system-for-fish-farming',
  'title': 'Development of water quality monitoring system for fish farming',
  'year': 2025,
  'authors': 'Juffil B. Papolonias; Rabby Q. Lavilles; Joel I. Miano',
  'venue': 'Bulletin of Electrical Engineering and Informatics',
  'kind': 'JOURNAL',
  'citation_details': 'Volume 14, issue 4 · Pages 2962–2974',
  'date_label': 'First published online: 1 August 2025',
  'publisher': 'Institute of Advanced Engineering and Science',
  'doi': '10.11591/eei.v14i4.7673',
  'source_url': 'https://doi.org/10.11591/eei.v14i4.7673',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 11. ',
  'is_published': True,
  'sort_order': 10},
 {'slug': 'ict-enabled-technologies-for-pedestrian-safety-a-scoping-review',
  'title': 'ICT-enabled Technologies for Pedestrian Safety A Scoping Review',
  'year': 2025,
  'authors': 'Jyresa Mae Amboang; Adrian Galido; Apple Rose B. Alce',
  'venue': 'PACIS 2025 Proceedings',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Paper PACIS 2025-1797',
  'date_label': '2025',
  'publisher': 'Association for Information Systems',
  'doi': '',
  'source_url': 'https://aisel.aisnet.org/pacis2025/iot_smartcity/iot_smartcity/7/',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 12. ',
  'is_published': True,
  'sort_order': 11},
 {'slug': 'developing-a-computer-vision-model-to-classify-abaca-fibers-using-yolov8',
  'title': 'Developing a Computer Vision Model to Classify Abaca Fibers Using YOLOv8',
  'year': 2025,
  'authors': 'Kenneth D. Ligutom; Leah A. Alindayo; Paul Rodolf P. Castor; Maria Fe P. Bahinting',
  'venue': 'Journal of Information Systems Engineering and Management',
  'kind': 'JOURNAL',
  'citation_details': 'Volume 10, issue 19s · Pages 352–361',
  'date_label': 'First published online: 12 March 2025',
  'publisher': 'Science Research Society',
  'doi': '10.52783/jisem.v10i19s.3035',
  'source_url': 'https://doi.org/10.52783/jisem.v10i19s.3035',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 13. Full author list from publisher page; Crossref deposit is '
                 'incomplete.',
  'is_published': True,
  'sort_order': 12},
 {'slug': 'are-we-inclusive-accessibility-challenges-in-philippine-e-government-websites',
  'title': 'Are We Inclusive? Accessibility Challenges in Philippine E-Government Websites',
  'year': 2025,
  'authors': 'Paul Bokingkito Jr.; Jerame Beloy; Jerina Jean Ecleo; Apple Rose Alce; Nenen Borinaga; Adrian '
             'Galido',
  'venue': 'Informatics',
  'kind': 'JOURNAL',
  'citation_details': 'Volume 12, issue 2 · Article 41',
  'date_label': 'First published online: 15 April 2025',
  'publisher': 'MDPI AG',
  'doi': '10.3390/informatics12020041',
  'source_url': 'https://doi.org/10.3390/informatics12020041',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 14. ',
  'is_published': True,
  'sort_order': 13},
 {'slug': 'computer-vision-based-detection-and-monitoring-system-for-mature-coconut-fruits-with-a-web-dashboard-visualization-platform',
  'title': 'Computer-Vision-Based Detection and Monitoring System for Mature Coconut Fruits with a Web '
           'Dashboard Visualization Platform',
  'year': 2024,
  'authors': 'Samfford S. Cabaluna; Maria Fe P. Bahinting; Leah A. Alindayo',
  'venue': 'International Journal of Advanced Computer Science and Applications',
  'kind': 'JOURNAL',
  'citation_details': 'Volume 15, issue 11 · Pages 767–772',
  'date_label': '2024',
  'publisher': 'The Science and Information Organization',
  'doi': '10.14569/ijacsa.2024.0151175',
  'source_url': 'https://doi.org/10.14569/ijacsa.2024.0151175',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 15. ',
  'is_published': True,
  'sort_order': 14},
 {'slug': 'development-of-an-image-based-reverse-vending-machine-using-raspberry-pi',
  'title': 'Development of an Image-Based Reverse Vending Machine Using Raspberry Pi',
  'year': 2024,
  'authors': 'Francis Miguel Colaljo; Kent Roian Basit; Rochelle James Jaudian; Apple Rose Alce; Paul Rodolf '
             'Castor; Paul Jr. Bokingkito; Antonio Marajas; Stefany Mae Caparida; Adrian Galido',
  'venue': 'Lecture Notes in Networks and Systems · Novel and Intelligent Digital Systems: Proceedings of '
           'the 4th International Conference (NiDS 2024)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 1170 · Pages 102–112',
  'date_label': 'First published online: 16 October 2024',
  'publisher': 'Springer Nature Switzerland',
  'doi': '10.1007/978-3-031-73344-4_8',
  'source_url': 'https://doi.org/10.1007/978-3-031-73344-4_8',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 16. ',
  'is_published': True,
  'sort_order': 15},
 {'slug': 'eyeway-an-artificial-intelligence-of-things-pothole-detection-system-with-map-visualization',
  'title': 'Eyeway: An Artificial Intelligence Of Things Pothole Detection System With Map Visualization',
  'year': 2024,
  'authors': 'Leonhel V. Fortin; Arjean Rose V. Delos Santos; Pul Joven B. Cagud; Paul Rodolf Castor; Orven '
             'E. Llantos',
  'venue': 'Procedia Computer Science',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 251 · Pages 216–223',
  'date_label': '2024',
  'publisher': 'Elsevier BV',
  'doi': '10.1016/j.procs.2024.11.103',
  'source_url': 'https://doi.org/10.1016/j.procs.2024.11.103',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 17. ',
  'is_published': True,
  'sort_order': 16},
 {'slug': 'design-and-development-of-a-university-outdoor-air-quality-monitoring-system',
  'title': 'Design and Development of a University Outdoor Air Quality Monitoring System',
  'year': 2024,
  'authors': 'Paul Rodolf P. Castor; Michael A. Nabua; Paul B. Bokingkito, Jr.; Apple Rose B. Alce; Adrian '
             'P. Galido',
  'venue': 'Procedia Computer Science',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 234 · Pages 1697–1704',
  'date_label': '2024',
  'publisher': 'Elsevier BV',
  'doi': '10.1016/j.procs.2024.03.175',
  'source_url': 'https://doi.org/10.1016/j.procs.2024.03.175',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 18. ',
  'is_published': True,
  'sort_order': 17},
 {'slug': 'automated-safe-awd-rice-irrigation-scheduling-using-low-power-wan-technology',
  'title': 'Automated Safe AWD Rice Irrigation Scheduling using Low-Power WAN Technology',
  'year': 2024,
  'authors': 'Apple Rose B. Alce; Michael A. Nabua; Adrian P. Galido',
  'venue': 'Procedia Computer Science',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 234 · Pages 1769–1776',
  'date_label': '2024',
  'publisher': 'Elsevier BV',
  'doi': '10.1016/j.procs.2024.03.184',
  'source_url': 'https://doi.org/10.1016/j.procs.2024.03.184',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 19. ',
  'is_published': True,
  'sort_order': 18},
 {'slug': 'optimizing-drying-efficiency-through-an-iot-based-direct-solar-dryer-system-integration-of-web-data-logger-and-sms-notification',
  'title': 'Optimizing Drying Efficiency Through an IoT-based Direct Solar Dryer System: Integration of Web '
           'Data Logger and SMS Notification',
  'year': 2023,
  'authors': 'Joel I. Miano; Michael A. Nabua; Alexander R. Gaw; Apple Rose B. Alce; Cris Argie M. Ecleo; '
             'Jewelane V. Repulle; Jaafar J. Omar',
  'venue': 'International Journal of Advanced Computer Science and Applications',
  'kind': 'JOURNAL',
  'citation_details': 'Volume 14, issue 7',
  'date_label': '2023',
  'publisher': 'The Science and Information Organization',
  'doi': '10.14569/ijacsa.2023.0140726',
  'source_url': 'https://doi.org/10.14569/ijacsa.2023.0140726',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 20. ',
  'is_published': True,
  'sort_order': 19},
 {'slug': 'rural-road-pavement-panel-detection-with-unmanned-aerial-vehicles',
  'title': 'Rural Road Pavement Panel Detection with Unmanned Aerial Vehicles',
  'year': 2023,
  'authors': 'Melody Mae O. Maluya; Earl Ryan M. Aleluya; Francis Jann A. Alagon; Steve E. Clar; Carl John '
             'O. Salaan; Joel G. Opon; Maria Fe P. Bahinting',
  'venue': '2023 IEEE 15th International Conference on Humanoid, Nanotechnology, Information Technology, '
           'Communication and Control, Environment, and Management (HNICEM)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Pages 1–6',
  'date_label': '2023',
  'publisher': 'IEEE',
  'doi': '10.1109/hnicem60674.2023.10589124',
  'source_url': 'https://doi.org/10.1109/hnicem60674.2023.10589124',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 21. ',
  'is_published': True,
  'sort_order': 20},
 {'slug': 'mask-hairnet-and-handwash-detection-system-for-food-manufacturing-health-and-safety-monitoring',
  'title': 'Mask, Hairnet, and Handwash Detection System for Food Manufacturing Health and Safety Monitoring',
  'year': 2023,
  'authors': 'Collien Princess C. Pepito; Earl Ryan M. Aleluya; Francis Jann A. Alagon; Steve E. Clar; Jared '
             'Jan A. Abayan; Carl John O. Salaan; Maria Fe P. Bahinting',
  'venue': '2023 IEEE 15th International Conference on Humanoid, Nanotechnology, Information Technology, '
           'Communication and Control, Environment, and Management (HNICEM)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Pages 1–6',
  'date_label': '2023',
  'publisher': 'IEEE',
  'doi': '10.1109/hnicem60674.2023.10589183',
  'source_url': 'https://doi.org/10.1109/hnicem60674.2023.10589183',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 22.  Corrected DOI: supplied 10589006 belongs to eggplant '
                 'paper; 10589183 identifies this paper.',
  'is_published': True,
  'sort_order': 21},
 {'slug': 'eggplant-leaf-semantic-segmentation-in-aerial-imagery-for-precision-agriculture',
  'title': 'Eggplant Leaf Semantic Segmentation in Aerial Imagery for Precision Agriculture',
  'year': 2023,
  'authors': 'Nouran M. Usman; Earl Ryan M. Aleluya; Steve E. Clar; Francis Jann A. Alagon; Carl John O. '
             'Salaan; Maria Fe P. Bahinting',
  'venue': '2023 IEEE 15th International Conference on Humanoid, Nanotechnology, Information Technology, '
           'Communication and Control, Environment, and Management (HNICEM)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Pages 1–6',
  'date_label': '2023',
  'publisher': 'IEEE',
  'doi': '10.1109/hnicem60674.2023.10589006',
  'source_url': 'https://doi.org/10.1109/hnicem60674.2023.10589006',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 23. ',
  'is_published': True,
  'sort_order': 22},
 {'slug': 'ground-robot-detection-for-collaborative-uav-ugv-alignment-and-retrieval-operations',
  'title': 'Ground Robot Detection for Collaborative UAV-UGV Alignment and Retrieval Operations',
  'year': 2023,
  'authors': 'Jamaica Mae L. Pepito; Earl Ryan M. Aleluya; John Mel A. Bolaybolay; Francis Jann A. Alagon; '
             'Steve E. Clar; Jeanette C. Pao; Carl John O. Salaan; Sherwin A. Guirnaldo; Maria Fe P. '
             'Bahinting',
  'venue': '2023 IEEE 15th International Conference on Humanoid, Nanotechnology, Information Technology, '
           'Communication and Control, Environment, and Management (HNICEM)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Pages 1–6',
  'date_label': '2023',
  'publisher': 'IEEE',
  'doi': '10.1109/hnicem60674.2023.10589261',
  'source_url': 'https://doi.org/10.1109/hnicem60674.2023.10589261',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 24. ',
  'is_published': True,
  'sort_order': 23},
 {'slug': 'detecting-persons-in-river-quarry-operations-aerial-surveillance-for-flood-pre-disaster-monitoring',
  'title': 'Detecting Persons in River Quarry Operations: Aerial Surveillance for Flood Pre-Disaster '
           'Monitoring',
  'year': 2023,
  'authors': 'Rochelle F. Madulara; Earl Ryan M. Aleluya; Jeanette C. Pao; Steve E. Clar; Francis Jann A. '
             'Alagon; Carl John O. Salaan; Maria Fe P. Bahinting',
  'venue': '2023 IEEE 15th International Conference on Humanoid, Nanotechnology, Information Technology, '
           'Communication and Control, Environment, and Management (HNICEM)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Pages 1–6',
  'date_label': '2023',
  'publisher': 'IEEE',
  'doi': '10.1109/hnicem60674.2023.10589218',
  'source_url': 'https://doi.org/10.1109/hnicem60674.2023.10589218',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 25. ',
  'is_published': True,
  'sort_order': 24},
 {'slug': 'development-of-a-wireless-sensor-node-for-storage-bin-volume-measurement',
  'title': 'Development of A Wireless Sensor Node for Storage Bin Volume Measurement',
  'year': 2023,
  'authors': 'Jaafar J. Omar; Earl Ryan M. Aleluya; Steve E. Clar; Jeanette C. Pao; Carl John O. Salaan; '
             'Maria Fe P. Bahinting; Joel I. Miano',
  'venue': '2023 IEEE 15th International Conference on Humanoid, Nanotechnology, Information Technology, '
           'Communication and Control, Environment, and Management (HNICEM)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Pages 1–6',
  'date_label': '2023',
  'publisher': 'IEEE',
  'doi': '10.1109/hnicem60674.2023.10589056',
  'source_url': 'https://doi.org/10.1109/hnicem60674.2023.10589056',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 26. ',
  'is_published': True,
  'sort_order': 25},
 {'slug': 'exploring-smart-city-analytical-framework-evidence-from-select-case-studies',
  'title': 'Exploring Smart City Analytical Framework: Evidence from Select Case Studies',
  'year': 2023,
  'authors': 'Apple Rose Alce; Jerina Jean Ecleo; Adrian Galido',
  'venue': 'Lecture Notes in Networks and Systems · Novel & Intelligent Digital Systems: Proceedings of the '
           '3rd International Conference (NiDS 2023)',
  'kind': 'PROCEEDINGS',
  'citation_details': 'Volume 783 · Pages 164–175',
  'date_label': 'First published online: 23 September 2023',
  'publisher': 'Springer Nature Switzerland',
  'doi': '10.1007/978-3-031-44097-7_17',
  'source_url': 'https://doi.org/10.1007/978-3-031-44097-7_17',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 27. ',
  'is_published': True,
  'sort_order': 26},
 {'slug': 'unraveling-the-complex-interdependencies-of-sdg-targets-in-the-csi-nexus-through-network-analysis-and-visualization',
  'title': 'Unraveling the Complex Interdependencies of SDG Targets in the CSI Nexus Through Network '
           'Analysis and Visualization',
  'year': 2023,
  'authors': 'Ernesto Empig; Ahmet Sivacioglu; Renato Pacaldo; Peter Suson; Rabby Lavilles; Maria Rizalia '
             'Teves; Maria Cecilia Ferolin; Ruben  F. Amparado, Jr.',
  'venue': 'SSRN',
  'kind': 'PREPRINT',
  'citation_details': '22 pages',
  'date_label': 'Posted 19 April 2023; written 30 March 2023',
  'publisher': 'Elsevier BV',
  'doi': '10.2139/ssrn.4404970',
  'source_url': 'https://doi.org/10.2139/ssrn.4404970',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 28. ',
  'is_published': True,
  'sort_order': 27},
 {'slug': 'climate-change-sustainable-forest-management-ict-nexus-and-the-sdg-2030-a-systems-thinking-approach',
  'title': 'Climate Change, Sustainable Forest Management, ICT Nexus, and the SDG 2030: A Systems Thinking '
           'Approach',
  'year': 2023,
  'authors': 'Ernesto E. Empig; Ahmet Sivacioğlu; Renato S. Pacaldo; Peter D. Suson; Rabby Q. Lavilles; '
             'Maria Rizalia Y. Teves; Maria Cecilia M. Ferolin; Ruben F. Amparado Jr.',
  'venue': 'Sustainability',
  'kind': 'JOURNAL',
  'citation_details': 'Volume 15, issue 8 · Article 6712',
  'date_label': 'First published online: 15 April 2023',
  'publisher': 'MDPI AG',
  'doi': '10.3390/su15086712',
  'source_url': 'https://doi.org/10.3390/su15086712',
  'source_note': 'Department-supplied publication list; DOI/Crossref and publisher records reviewed 6 '
                 'October 2026. Original row 29. ',
  'is_published': True,
  'sort_order': 28}]

def add_publication_records(apps, schema_editor):
    Publication = apps.get_model("research", "PublicationRecord")
    for record in RECORDS:
        defaults = dict(record)
        slug = defaults.pop("slug")
        Publication.objects.using(schema_editor.connection.alias).get_or_create(slug=slug, defaults=defaults)

class Migration(migrations.Migration):
    dependencies = [("research", "0005_publicationrecord")]
    operations = [migrations.RunPython(add_publication_records, migrations.RunPython.noop)]
