# Generated by Django 6.0.3 on 2026-03-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='About the Department', max_length=255)),
                ('overview', models.TextField()),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('outcomes_mapping_note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.TextField(blank=True)),
                ('primary_cta_label', models.CharField(blank=True, max_length=100)),
                ('primary_cta_url', models.CharField(blank=True, max_length=255)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=100)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='heroes/')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuickStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Department of Computer Applications', max_length=255)),
                ('short_name', models.CharField(default='DCA', max_length=50)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
