# Generated by Django 6.0.8 on 2026-10-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_public_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('reporting_year', models.PositiveIntegerField(help_text='Department reporting year; not a verified completion or publication date.')),
                ('summary', models.TextField(help_text='Brief plain-language description; avoid unsupported performance or novelty claims.')),
                ('kind', models.CharField(choices=[('GAME', 'Games and learning'), ('SENSING', 'Sensing and monitoring'), ('INTERFACE', 'Displays and interfaces'), ('TIMING', 'Clocks and timers'), ('CONTROL', 'Controllers')], max_length=20)),
                ('creator_credits', models.TextField(blank=True, help_text='Credits as confirmed on the source page; do not infer student, adviser or faculty roles.')),
                ('source_url', models.URLField(help_text='Public project link without private access tokens.', max_length=500)),
                ('source_note', models.TextField(blank=True, help_text='Internal provenance and verification notes.')),
            ],
            options={
                'ordering': ['-reporting_year', 'sort_order', 'title'],
            },
        ),
    ]
