# Generated by Django 6.0.3 on 2026-03-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('degree_level', models.CharField(choices=[('UNDERGRAD', 'Undergraduate'), ('GRAD', 'Graduate')], max_length=20)),
                ('overview', models.TextField()),
                ('career_opportunities', models.TextField(blank=True)),
                ('admission_requirements', models.TextField(blank=True)),
                ('faq_intro', models.TextField(blank=True)),
                ('curriculum_pdf', models.FileField(blank=True, null=True, upload_to='programs/curricula/')),
                ('evidence_documents', models.ManyToManyField(blank=True, related_name='programs', to='quality.evidencedocument')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
    ]
