# Generated by Django 6.0.6 on 2026-07-01 03:00

import django.db.models.deletion
from django.db import migrations, models


PLACEHOLDER = "To be provided by the Department."


def _set_if_blank(program, field, value):
    if not getattr(program, field):
        setattr(program, field, value)


def seed_program_page_fields(apps, schema_editor):
    Program = apps.get_model("academics", "Program")
    ProgramDocument = apps.get_model("academics", "ProgramDocument")

    seeds = {
        "BSCA": {
            "formal_description": "An undergraduate academic program in applied computing and computer applications with a culminating Undergraduate Thesis.",
            "academic_orientation": "Undergraduate applied computing and computer applications.",
            "intended_learners": "Prospective undergraduate students seeking formal preparation in applied computing, software systems, embedded systems, Internet of Things, and related computing domains.",
            "culminating_requirement": "Undergraduate Thesis",
            "program_goals": "\n".join([
                "Provide undergraduate preparation in applied computing and computer applications.",
                "Develop student competence in software systems, embedded systems, Internet of Things, and related computing domains.",
                "Prepare students for supervised thesis work, professional practice, further study, and responsible participation in computing-related work.",
            ]),
            "academic_areas": "\n".join([
                "Applied computing and computer applications.",
                "Software systems and systems development.",
                "Embedded systems and Internet of Things.",
                "Undergraduate research and thesis work.",
            ]),
            "curriculum_structure": "\n".join([
                "General education, institutional, and foundational courses.",
                "Computing, software systems, embedded systems, and Internet of Things courses.",
                "Research preparation and Undergraduate Thesis.",
                "Supervised industry exposure, if applicable, to be validated by the Department.",
            ]),
            "thesis_information": "\n".join([
                "The culminating academic requirement is the Undergraduate Thesis.",
                "Official thesis procedures, advising arrangements, and assessment documentation are To be provided by the Department.",
            ]),
            "student_support": "\n".join([
                "Academic advising arrangements are To be provided by the Department.",
                "Laboratory, software, and student support information are To be provided by the Department.",
            ]),
            "contact_information": PLACEHOLDER,
            "seo_title": "Bachelor of Science in Computer Applications",
            "seo_description": "Formal undergraduate program information for the Bachelor of Science in Computer Applications of the Department of Computer Applications, MSU-IIT.",
            "og_title": "Bachelor of Science in Computer Applications",
            "og_description": "Undergraduate academic program in applied computing and computer applications with a culminating Undergraduate Thesis.",
            "documents": [
                ("BSCA curriculum", "CURRICULUM", 10),
                ("Undergraduate admission guide", "ADMISSION", 20),
                ("BSCA program brochure", "BROCHURE", 30),
                ("Student handbook or advising guide", "HANDBOOK", 40),
            ],
        },
        "MSCA": {
            "formal_description": "A graduate academic program in advanced computer applications, applied computing research, and related computing domains with a culminating Master’s Thesis.",
            "academic_orientation": "Graduate applied computing research and advanced computer applications.",
            "intended_learners": "Prospective graduate students seeking advanced preparation in applied computing research, advanced computer applications, and thesis-based scholarly work.",
            "culminating_requirement": "Master’s Thesis",
            "program_goals": "\n".join([
                "Develop graduate-level competence in applied computing research and advanced computer applications.",
                "Prepare students to conduct thesis-based scholarly work using appropriate methods and ethical research practice.",
                "Support progression to advanced professional, academic, research, or doctoral pathways.",
            ]),
            "academic_areas": "\n".join([
                "Applied computing research.",
                "Advanced computer applications.",
                "Embedded systems and Internet of Things.",
                "Analytics, intelligent systems, cloud computing, cybersecurity, and related computing domains, subject to Department validation.",
            ]),
            "curriculum_structure": "\n".join([
                "Graduate coursework in advanced computer applications and applied computing research.",
                "Research preparation and thesis development.",
                "Master’s Thesis as the culminating academic requirement.",
                "Bridging or prerequisite preparation, if applicable, to be validated by the Department.",
            ]),
            "thesis_information": "\n".join([
                "The culminating academic requirement is the Master’s Thesis.",
                "Official thesis procedures, advising arrangements, and assessment documentation are To be provided by the Department.",
            ]),
            "student_support": "\n".join([
                "Graduate advising and faculty supervision information are To be provided by the Department.",
                "Research support, laboratory access, and graduate student resources are To be provided by the Department.",
            ]),
            "contact_information": PLACEHOLDER,
            "seo_title": "Master of Science in Computer Applications",
            "seo_description": "Formal graduate program information for the Master of Science in Computer Applications of the Department of Computer Applications, MSU-IIT.",
            "og_title": "Master of Science in Computer Applications",
            "og_description": "Graduate academic program in advanced computer applications and applied computing research with a culminating Master’s Thesis.",
            "documents": [
                ("MSCA curriculum", "CURRICULUM", 10),
                ("Graduate admission guide", "ADMISSION", 20),
                ("MSCA program brochure", "BROCHURE", 30),
                ("Graduate handbook or thesis guide", "HANDBOOK", 40),
            ],
        },
    }

    for code, values in seeds.items():
        try:
            program = Program.objects.get(code=code)
        except Program.DoesNotExist:
            continue

        for field, value in values.items():
            if field != "documents":
                _set_if_blank(program, field, value)
        program.save()

        for title, document_type, sort_order in values["documents"]:
            ProgramDocument.objects.get_or_create(
                program=program,
                title=title,
                defaults={
                    "document_type": document_type,
                    "note": PLACEHOLDER,
                    "sort_order": sort_order,
                    "is_public": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_program_peos_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='academic_areas',
            field=models.TextField(blank=True, help_text='Enter one academic or research area per line.'),
        ),
        migrations.AddField(
            model_name='program',
            name='academic_orientation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='contact_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='culminating_requirement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='curriculum_structure',
            field=models.TextField(blank=True, help_text='Enter one curriculum structure item per line.'),
        ),
        migrations.AddField(
            model_name='program',
            name='formal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='intended_learners',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='program_goals',
            field=models.TextField(blank=True, help_text='Enter one program goal per line.'),
        ),
        migrations.AddField(
            model_name='program',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='student_support',
            field=models.TextField(blank=True, help_text='Enter one student support or facility item per line.'),
        ),
        migrations.AddField(
            model_name='program',
            name='thesis_information',
            field=models.TextField(blank=True, help_text='Enter thesis information using official Department terminology.'),
        ),
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CURRICULUM', 'Curriculum'), ('ADMISSION', 'Admission guide'), ('BROCHURE', 'Program brochure'), ('HANDBOOK', 'Student handbook or advising guide'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='programs/documents/')),
                ('url', models.URLField(blank=True)),
                ('note', models.CharField(blank=True, default='To be provided by the Department.', max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academics.program')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.RunPython(seed_program_page_fields, migrations.RunPython.noop),
    ]
