# Generated by Django 6.0.8 on 2026-10-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_department_prospectuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='completion_requirements',
            field=models.TextField(blank=True, help_text='One prospectus-based completion requirement per line.'),
        ),
        migrations.AddField(
            model_name='program',
            name='content_reviewed_on',
            field=models.DateField(blank=True, help_text='Date the public website summary was reviewed; not a curriculum approval date.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='study_plan_guidance',
            field=models.TextField(blank=True, help_text='One study term and explanation per line, separated by a colon.'),
        ),
    ]
