# Generated by Django 6.0.8 on 2026-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_program_study_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='admissions_url',
            field=models.URLField(blank=True, help_text='Official university or college application and admission guidance.'),
        ),
    ]
