# Generated by Django 6.0.8 on 2026-10-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_msca_admission_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='admissions_portal_url',
            field=models.URLField(blank=True, help_text='Official application portal, if separate from the admission guide.'),
        ),
    ]
