# Generated by Django 6.0.8 on 2026-10-06 08:07

import apps.academics.sojt_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_msca_graduate_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOJTGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='bsca', unique=True)),
                ('content', models.JSONField(help_text='Structured public guide; see docs/sojt-process-guide.md for the schema and source map.', validators=[apps.academics.sojt_schema.validate_guide])),
                ('is_published', models.BooleanField(default=False)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('approval_reference', models.CharField(blank=True, help_text="Internal reference to the Department's approval and applicability review; never exposed by the API.", max_length=255)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal editorial notes only. Never put student, medical, complaint or agreement records in the guide.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
