# Generated by Django 6.0.8 on 2026-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_bsca_additional_written_exam_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='registrar/forms/')),
                ('url', models.URLField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
