# Generated by Django 6.0.8 on 2026-10-09 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_registrar_forms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('passing_grades', models.JSONField(default=list, help_text='Verified passing grade tokens, e.g. strings from the campus grading legend. Unknown grades require review.')),
                ('nonpassing_grades', models.JSONField(default=list, help_text='Verified failed, withdrawn or incomplete tokens. Must not overlap passing grades.')),
                ('is_active', models.BooleanField(default=True)),
                ('policy_reference', models.CharField(help_text='Department verification or grading-legend reference.', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('source', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('capacity', models.PositiveIntegerField(default=80)),
                ('occupied', models.PositiveIntegerField(default=0, help_text='Existing students; exclude accepted requests already counted by this portal.')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('term', 'year'), name='evaluation_term_year_capacity')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('units', models.DecimalField(decimal_places=1, max_digits=4)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('semester', models.PositiveSmallIntegerField(default=0)),
                ('is_elective', models.BooleanField(default=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.evaluationcurriculum')),
            ],
            options={
                'ordering': ['year', 'semester', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_digest', models.CharField(editable=False, max_length=64)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('applicant_type', models.CharField(choices=[('shiftee', 'Shiftee'), ('transferee', 'Transferee')], max_length=12)),
                ('school', models.CharField(max_length=150)),
                ('within_msu', models.BooleanField(default=False)),
                ('current_program', models.CharField(max_length=150)),
                ('intended_term', models.CharField(max_length=100)),
                ('document', models.BinaryField()),
                ('document_name', models.CharField(editable=False, max_length=200)),
                ('draft', models.JSONField(default=dict, editable=False)),
                ('status', models.CharField(choices=[('adviser', 'Adviser review'), ('chairperson', 'Chairperson review'), ('accepted', 'Accepted'), ('not_accepted', 'Not accepted')], default='adviser', max_length=20)),
                ('records_verified', models.BooleanField(default=False, help_text='Adviser checked the transcript, grades and MSU affiliation against submitted entries.')),
                ('adviser_notes', models.TextField(blank=True)),
                ('capacity_override_reason', models.TextField(blank=True)),
                ('student_feedback', models.TextField(blank=True, help_text='Released to the student only after the chairperson finalizes the decision.')),
                ('adviser_approved_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('adviser_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adviser_approvals', to=settings.AUTH_USER_MODEL)),
                ('assigned_adviser', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.evaluationcampus')),
                ('capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='academics.evaluationcapacity')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.evaluationcurriculum')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'permissions': [('review_evaluation', 'Review and endorse evaluation as adviser'), ('decide_evaluation', 'Finalize evaluation as chairperson')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('units', models.DecimalField(decimal_places=1, max_digits=4)),
                ('grade', models.CharField(max_length=30)),
                ('automatic_result', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=250)),
                ('course_snapshot', models.JSONField(default=dict)),
                ('decision', models.CharField(blank=True, choices=[('credit', 'Credit'), ('no_credit', 'Do not credit')], max_length=12)),
                ('review_note', models.CharField(blank=True, max_length=250)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.evaluationcourse')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.evaluationrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationcourse',
            constraint=models.UniqueConstraint(fields=('curriculum', 'code'), name='evaluation_curriculum_course'),
        ),
    ]
