# Generated by Django 6.0.8 on 2026-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_evaluation_prospectus'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubject',
            name='source_record',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='evaluationsubject',
            name='grade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='evaluationsubject',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
