# Generated by Django 6.0.8 on 2026-10-09 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_evaluationsubject_source_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(choices=[('FOUNDATIONS', 'Foundations'), ('EMBEDDED', 'Embedded systems'), ('IOT', 'Internet of Things')], max_length=40)),
                ('provider', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ALL', 'All levels')], max_length=30)),
                ('resource_type', models.CharField(default='Reading guide', max_length=40)),
                ('access_note', models.CharField(max_length=255)),
                ('activity', models.CharField(blank=True, max_length=500)),
                ('start_here', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
    ]
