# Generated by Django 6.0.8 on 2026-10-09 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_learning_resource_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='source_collection',
            field=models.CharField(blank=True, help_text='ROADMAP identifies material adapted under CC BY-SA 4.0; blank identifies department-added entries.', max_length=40),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='source_section',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='topic',
            field=models.CharField(choices=[('FOUNDATIONS', 'Foundations'), ('PROGRAMMING', 'Programming'), ('EMBEDDED', 'Devices & embedded systems'), ('IOT', 'IoT & connectivity'), ('DATA', 'Data, signals & AI'), ('SOFTWARE', 'Software tools, testing & security'), ('EXPLORE', 'Projects & learning support'), ('ADVANCED', 'Optional specialist topics')], max_length=40),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='url',
            field=models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
