# Generated by Django 6.0.8 on 2026-10-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_full_learning_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
