# Generated by Django 6.0.8 on 2026-10-09 09:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniEmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('request_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('JOB', 'Career opportunity'), ('STUDY', 'Further study'), ('TRAINING', 'Training'), ('EVENT', 'Event'), ('MENTORING', 'Mentoring')], max_length=20)),
                ('description', models.TextField()),
                ('provider', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('closes_on', models.DateField(blank=True, null=True)),
                ('source_note', models.TextField(blank=True, help_text='Internal verification notes; not shown publicly.')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlumniSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepting_updates', models.BooleanField(default=False)),
                ('contact_label', models.CharField(default='Department chairperson', max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('privacy_notice', models.TextField(blank=True, help_text='Department-approved purpose, access, correction/deletion process, and retention notice.')),
                ('notice_version', models.CharField(blank=True, max_length=80)),
                ('retention_days', models.PositiveIntegerField(blank=True, help_text='Delete records after this many days without an alumni update, using the purge command.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36500)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlumniUpdateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('bsca_year', models.PositiveIntegerField(blank=True, null=True)),
                ('msca_year', models.PositiveIntegerField(blank=True, null=True)),
                ('career_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-employed'), ('FURTHER_STUDY', 'Further study'), ('SEEKING_WORK', 'Seeking work'), ('OTHER', 'Other activities'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=30)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('interests', models.CharField(blank=True, max_length=500)),
                ('preferred_contact', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], default='EMAIL', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('receive_updates', models.BooleanField(default=False)),
                ('willing_to_mentor', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField()),
                ('consented_at', models.DateTimeField()),
                ('notice_version', models.CharField(max_length=80)),
                ('alumni_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending affiliation review'), ('VERIFIED', 'Alumni affiliation verified'), ('UNCONFIRMED', 'Affiliation unconfirmed')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
