# Generated by Django 6.0.8 on 2026-10-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_initial_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnisettings',
            options={'verbose_name': 'alumni update settings', 'verbose_name_plural': 'alumni update settings'},
        ),
    ]
