# Generated by Django 6.0.8 on 2026-10-09 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_chairperson_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='access_key_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='alignment_explanation',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='career_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='career_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='duties',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='exam_details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='exam_status',
            field=models.CharField(blank=True, choices=[('', 'Not provided'), ('PASSED', 'Passed'), ('NOT_PASSED', 'Not passed'), ('NOT_TAKEN', 'Not taken / not applicable')], max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='further_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='network_interests',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='professional_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='program_feedback',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='residence_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='residence_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('', 'Not provided'), ('M', 'Male'), ('F', 'Female'), ('OTHER', 'Another description'), ('UNDISCLOSED', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='skills_used',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='study_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='study_program',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='work_alignment',
            field=models.CharField(blank=True, choices=[('', 'Not provided'), ('ALIGNED', 'Aligned'), ('PARTLY', 'Partly aligned'), ('NOT_ALIGNED', 'Not aligned'), ('UNSURE', 'Unsure / not applicable')], max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='work_arrangement',
            field=models.CharField(blank=True, choices=[('', 'Not provided'), ('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='work_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='work_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumnisettings',
            name='access_keys_enabled',
            field=models.BooleanField(default=False, help_text='Allow alumni to register and return with a private access key. Affiliation is reviewed separately.'),
        ),
        migrations.AddField(
            model_name='alumnisettings',
            name='retain_indefinitely',
            field=models.BooleanField(default=False, help_text='Keep alumni accounts and career history without automatic expiry. Correction/deletion requests remain available.'),
        ),
        migrations.AddField(
            model_name='alumniupdatesession',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlumniCareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_kind', models.CharField(choices=[('CURRENT', 'Current activity update'), ('HISTORICAL', 'Previous role or activity')], default='CURRENT', max_length=20)),
                ('career_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-employed'), ('FURTHER_STUDY', 'Further study'), ('SEEKING_WORK', 'Seeking work'), ('OTHER', 'Other activities'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('work_city', models.CharField(blank=True, max_length=150)),
                ('work_country', models.CharField(blank=True, max_length=100)),
                ('work_arrangement', models.CharField(blank=True, max_length=20)),
                ('duties', models.TextField(blank=True)),
                ('skills_used', models.CharField(blank=True, max_length=1000)),
                ('work_alignment', models.CharField(blank=True, max_length=20)),
                ('alignment_explanation', models.TextField(blank=True)),
                ('career_start', models.DateField(blank=True, null=True)),
                ('career_end', models.DateField(blank=True, null=True)),
                ('further_study', models.BooleanField(default=False)),
                ('study_program', models.CharField(blank=True, max_length=200)),
                ('study_institution', models.CharField(blank=True, max_length=200)),
                ('exam_status', models.CharField(blank=True, max_length=20)),
                ('exam_details', models.CharField(blank=True, max_length=500)),
                ('program_feedback', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_history', to='alumni.alumniprofile')),
            ],
            options={
                'ordering': ['-reported_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='GraduateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('family_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('student_id', models.CharField(blank=True, max_length=40)),
                ('program', models.CharField(choices=[('BSCA', 'BSCA'), ('MSCA', 'MSCA')], max_length=4)),
                ('graduation_year', models.PositiveIntegerField()),
                ('graduation_period', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('landline', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('permanent_address', models.TextField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('alumni_profile', models.ForeignKey(blank=True, help_text='Link only after staff confirms this account belongs to the graduate. Imported contact data do not verify account ownership.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduate_records', to='alumni.alumniprofile')),
            ],
            options={
                'ordering': ['-graduation_year', 'program', 'family_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GraduateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('source_digest', models.CharField(max_length=64)),
                ('reporting_period', models.CharField(blank=True, max_length=100)),
                ('traced', models.BooleanField(blank=True, null=True)),
                ('employed', models.BooleanField(blank=True, null=True)),
                ('further_study', models.BooleanField(blank=True, null=True)),
                ('unemployed', models.BooleanField(blank=True, null=True)),
                ('aligned', models.BooleanField(blank=True, null=True)),
                ('exam_passed', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='alumni.graduaterecord')),
            ],
            options={
                'ordering': ['-imported_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('source_digest', 'source_sheet', 'source_row'), name='unique_graduate_source_row')],
            },
        ),
    ]
