# Generated by Django 6.0.8 on 2026-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alumniprofile_access_key_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniprofile',
            options={'permissions': [('reset_alumni_access', 'Reset an alumni access key after confirming identity')]},
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='bsca_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='family_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='landline',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='msca_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='permanent_address',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
