# Generated by Django 6.0.3 on 2026-03-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('educational_background', models.TextField(blank=True)),
                ('research_interests', models.TextField(blank=True)),
                ('courses_taught', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('awards', models.TextField(blank=True)),
                ('office', models.CharField(blank=True, max_length=255)),
                ('evidence_documents', models.ManyToManyField(blank=True, related_name='faculty_members', to='quality.evidencedocument')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
    ]
