# Generated by Django 6.0.8 on 2026-10-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_updated_faculty_profiles_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='transferred_from_dca',
            field=models.BooleanField(default=False, help_text='Transferred out of DCA; may also remain affiliated with MSCA. Record the destination and order in the home unit and assignment note.'),
        ),
    ]
