# Generated by Django 6.0.8 on 2026-10-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_pepito_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='prc_license_number',
            field=models.CharField(blank=True, help_text='License number supplied by the Department; not verification of current license validity.', max_length=32),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='faculty_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('active_full_time', 'Active Full-Time'), ('study_leave', 'Study Leave'), ('sabbatical_leave', 'Sabbatical Leave'), ('retired', 'Retired'), ('resigned', 'Resigned'), ('inactive_affiliation', 'Inactive Affiliation')], default='active', help_text='Use only when personnel type is Faculty.', max_length=32),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='service_classification',
            field=models.CharField(choices=[('active_dca_faculty', 'Active DCA Faculty'), ('affiliated_msca_faculty', 'Affiliated MSCA Faculty'), ('retired_dca_faculty', 'Retired DCA Faculty'), ('resigned_dca_faculty', 'Resigned DCA Faculty'), ('academic_staff', 'Academic Staff'), ('laboratory_personnel', 'Laboratory Personnel')], default='active_dca_faculty', help_text='Controls public directory grouping.', max_length=64),
        ),
    ]
