from django.db import migrations

PROFILES = [{'title': 'Ernesto E. Empig',
  'slug': 'ernesto-e-empig',
  'surname': 'Empig',
  'home_unit': 'School of Interdisciplinary Studies (SIS)',
  'specialization_areas': 'ICT Design and Development; CSI Nexus',
  'prc_license_number': '',
  'education': [{'degree_level': 'doctorate',
                 'degree_name': 'Doctor in Sustainable Development Studies (Sustainable Environmental '
                                'Education)',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2023,
                 'notes': ''},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Information Technology',
                 'institution': 'Ateneo de Davao University',
                 'year_completed': 2005,
                 'notes': ''},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Industrial Education (Electronics)',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 1993,
                 'notes': ''}]},
 {'title': 'Adrian P. Galido',
  'slug': 'adrian-p-galido',
  'surname': 'Galido',
  'home_unit': 'Department of Information Technology, College of Computer Studies',
  'specialization_areas': 'Digital Transformation; Strategic Planning; Public Policy',
  'prc_license_number': '',
  'education': [{'degree_level': 'other',
                 'degree_name': 'NUS Fellows Programme (Southeast Asia)',
                 'institution': 'Lee Kuan Yew School of Public Policy, National University of Singapore, '
                                'Singapore',
                 'year_completed': 2024,
                 'notes': 'Academic fellowship; not a degree.'},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Data Science',
                 'institution': 'Asian Institute of Management, Makati',
                 'year_completed': 2019,
                 'notes': ''},
                {'degree_level': 'doctorate',
                 'degree_name': 'Doctor of Philosophy in Management',
                 'institution': 'University of San Carlos, Cebu',
                 'year_completed': 2012,
                 'notes': ''},
                {'degree_level': 'masters',
                 'degree_name': 'Master in Technology Management',
                 'institution': 'University of the Philippines Diliman, Quezon City',
                 'year_completed': 2005,
                 'notes': ''},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Computer Science',
                 'institution': 'University of the Philippines Diliman, Quezon City',
                 'year_completed': 2000,
                 'notes': ''}]},
 {'title': 'Rabby Q. Lavilles',
  'slug': 'rabby-q-lavilles',
  'surname': 'Lavilles',
  'home_unit': 'Department of Information Technology, College of Computer Studies',
  'specialization_areas': 'Socio-Technical Systems; IT Adoption and Use',
  'prc_license_number': '',
  'education': [{'degree_level': 'doctorate',
                 'degree_name': 'Doctor in Information Technology',
                 'institution': 'De La Salle University, Manila',
                 'year_completed': 2018,
                 'notes': ''},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Information Technology',
                 'institution': 'De La Salle University, Manila',
                 'year_completed': 2010,
                 'notes': ''},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Business Administration (Information Systems)',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2002,
                 'notes': ''}]},
 {'title': 'Orven E. Llantos',
  'slug': 'orven-e-llantos',
  'surname': 'Llantos',
  'home_unit': 'Department of Computer Science, College of Computer Studies',
  'specialization_areas': 'Database; Software Engineering; Data Science; Social Network Analysis; Cloud '
                          'Computing',
  'prc_license_number': '',
  'education': [{'degree_level': 'doctorate',
                 'degree_name': 'Doctor of Philosophy in Computer Science',
                 'institution': 'Ateneo de Manila University, Manila, Philippines',
                 'year_completed': 2021,
                 'notes': ''},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Computer Applications',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2007,
                 'notes': ''},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Computer Science',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2000,
                 'notes': ''}]},
 {'title': 'Hareez V. Quimque',
  'slug': 'hareez-v-quimque',
  'surname': 'Quimque',
  'home_unit': 'Department of Electronics Engineering, College of Computer Engineering',
  'specialization_areas': 'Analog and Digital Integrated Circuits Design; Field Programmable Gate Arrays; '
                          'Power Electronics; Internet of Things; Digital Signal Processing; Embedded '
                          'Systems',
  'prc_license_number': '0050020',
  'education': [{'degree_level': 'doctorate',
                 'degree_name': 'Doctor of Philosophy in Electrical Engineering and Computer Science',
                 'institution': 'National Taipei University (NTPU)',
                 'year_completed': 2022,
                 'notes': ''},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Electrical Engineering (Integrated Circuits Design)',
                 'institution': 'National Taipei University (NTPU)',
                 'year_completed': 2010,
                 'notes': ''},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Electronics and Communications Engineering',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2006,
                 'notes': ''}]},
 {'title': 'Sherwin A. Guirnaldo',
  'slug': 'sherwin-a-guirnaldo',
  'surname': 'Guirnaldo',
  'home_unit': 'Department of Mechanical and Engineering Science, College of Engineering',
  'specialization_areas': 'Robotics; Control Systems; Applied Artificial Intelligence; Soft Computing; '
                          'Design Optimization; Biomedical Engineering',
  'prc_license_number': '',
  'education': [{'degree_level': 'doctorate',
                 'degree_name': 'Doctor of Philosophy in Robotics and Intelligent Systems',
                 'institution': 'Saga University',
                 'year_completed': 2004,
                 'notes': ''},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Computer Applications',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': None,
                 'notes': 'Completed qualification; year not supplied by the Department.'},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Mechanical Engineering',
                 'institution': 'Mindanao State University, Marawi',
                 'year_completed': None,
                 'notes': 'Completed qualification; year not supplied by the Department.'}]},
 {'title': 'Carl John O. Salaan',
  'slug': 'carl-john-o-salaan',
  'surname': 'Salaan',
  'home_unit': 'Department of Mechanical and Engineering Science, College of Engineering',
  'specialization_areas': 'Robotics; UAV Mechanism; Artificial Intelligence; Power Systems',
  'prc_license_number': '0041154',
  'education': [{'degree_level': 'doctorate',
                 'degree_name': 'Doctor of Philosophy in Information Science',
                 'institution': 'Tohoku University',
                 'year_completed': None,
                 'notes': 'Completed qualification; year not supplied by the Department.'},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Electrical Engineering',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2011,
                 'notes': ''},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Electrical Engineering',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2007,
                 'notes': ''}]},
 {'title': 'Cherry Mae G. Villame',
  'slug': 'cherry-mae-g-villame',
  'surname': 'Villame',
  'home_unit': 'Department of Computer Engineering and Mechatronics, College of Engineering',
  'specialization_areas': 'Programming languages and technologies: C, C++, HTML, Java, MySQL, PHP, MATLAB, '
                          'Python, Simulink, Scilab and Verilog; Computer Aided Engineering; Software '
                          'Development; Artificial Intelligence; Neural Networks; Robotics; Mechatronics',
  'prc_license_number': '',
  'education': [{'degree_level': 'doctorate',
                 'degree_name': 'Doctor of Engineering',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2021,
                 'notes': ''},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Computer Applications',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2014,
                 'notes': ''},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Computer Engineering',
                 'institution': 'University of Science and Technology of Southern Philippines',
                 'year_completed': 2011,
                 'notes': ''}]},
 {'title': 'Arnel D. Zamayla',
  'slug': 'arnel-d-zamayla',
  'surname': 'Zamayla',
  'home_unit': 'Department of Computer Engineering and Mechatronics, College of Engineering',
  'specialization_areas': 'Artificial Intelligence; Deep Learning; Answer Set Programming; Computer Vision',
  'prc_license_number': '',
  'education': [{'degree_level': 'doctorate',
                 'degree_name': 'Doctor of Philosophy in Mathematics and Computer Science (Artificial '
                                'Intelligence)',
                 'institution': 'Università della Calabria, Italy',
                 'year_completed': 2022,
                 'notes': ''},
                {'degree_level': 'other',
                 'degree_name': 'PhD internship',
                 'institution': 'Curtin University, Perth, Western Australia',
                 'year_completed': 2021,
                 'notes': 'Research internship; not a separate awarded degree.'},
                {'degree_level': 'masters',
                 'degree_name': 'Master of Science in Computer Applications',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2013,
                 'notes': ''},
                {'degree_level': 'bachelors',
                 'degree_name': 'Bachelor of Science in Computer Engineering',
                 'institution': 'MSU-Iligan Institute of Technology',
                 'year_completed': 2011,
                 'notes': ''}]}]

MARKER = "Allied faculty information supplied by the Department, 6 October 2026."


def import_allied_and_resigned(apps, schema_editor):
    Faculty = apps.get_model("people", "FacultyMember")
    Education = apps.get_model("people", "FacultyEducation")
    alias = schema_editor.connection.alias
    for order, source in enumerate(PROFILES):
        matches = list(Faculty.objects.using(alias).filter(title__icontains=source["surname"]))
        if len(matches) > 1:
            raise RuntimeError("Resolve duplicate faculty profiles for " + source["surname"])
        member = matches[0] if matches else Faculty.objects.using(alias).create(title=source["title"], slug=source["slug"], sort_order=100+order)
        if member.last_updated_note == MARKER:
            continue
        programs = member.supporting_programs or ""
        if "MSCA" not in programs.upper():
            programs = ", ".join(filter(None, [programs.strip(), "MSCA"]))
        Faculty.objects.using(alias).filter(pk=member.pk).update(title=source["title"], home_unit=source["home_unit"], specialization_areas=source["specialization_areas"], highest_degree="Doctoral Degree", prc_license_number=source["prc_license_number"], service_classification="affiliated_msca_faculty", supporting_programs=programs, active_affiliation=True, is_published=True, last_updated_note=MARKER)
        for index, education in enumerate(source["education"]):
            Education.objects.using(alias).update_or_create(faculty_id=member.pk, degree_name=education["degree_name"], institution=education["institution"], defaults={**education, "sort_order": index, "is_published": True})
    matches = list(Faculty.objects.using(alias).filter(title__icontains="Miano"))
    if len(matches) > 1:
        raise RuntimeError("Resolve duplicate Joel Miano profiles before recording resignation.")
    member = matches[0] if matches else Faculty.objects.using(alias).create(title="Joel I. Miano", slug="joel-i-miano")
    note = "Resignation from DCA confirmed by the Department, 6 October 2026. Effective date not supplied."
    if note not in member.appointment_or_assignment_note:
        Faculty.objects.using(alias).filter(pk=member.pk).update(title="Joel I. Miano", faculty_status="resigned", service_classification="resigned_dca_faculty", active_affiliation=False, is_published=True, appointment_or_assignment_note=(member.appointment_or_assignment_note.rstrip()+"\n\n"+note).strip())


class Migration(migrations.Migration):
    dependencies = [("people", "0008_facultymember_prc_license_number_and_more")]
    operations = [migrations.RunPython(import_allied_and_resigned, migrations.RunPython.noop)]
