# Generated by Django 6.0.8 on 2026-10-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_department_extension'),
        ('people', '0009_allied_and_resigned_faculty'),
        ('research', '0006_department_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Use only a role established by the source; conference author does not mean presenter.', max_length=100)),
                ('credited_name', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.conferencerecord')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extension.extensionproject')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_contributions', to='people.facultymember')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.publicationrecord')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.researchproject')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('conference__isnull', True), ('extension__isnull', True), ('publication__isnull', True), ('research__isnull', False)), models.Q(('conference__isnull', True), ('extension__isnull', True), ('publication__isnull', False), ('research__isnull', True)), models.Q(('conference__isnull', False), ('extension__isnull', True), ('publication__isnull', True), ('research__isnull', True)), models.Q(('conference__isnull', True), ('extension__isnull', False), ('publication__isnull', True), ('research__isnull', True)), _connector='OR'), name='faculty_contribution_one_source'), models.UniqueConstraint(fields=('faculty', 'research'), name='unique_faculty_research_credit'), models.UniqueConstraint(fields=('faculty', 'publication'), name='unique_faculty_publication_credit'), models.UniqueConstraint(fields=('faculty', 'conference'), name='unique_faculty_conference_credit'), models.UniqueConstraint(fields=('faculty', 'extension'), name='unique_faculty_extension_credit')],
            },
        ),
    ]
