# Generated by Django 6.0.8 on 2026-10-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_department_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyconference',
            name='reconciled_contribution',
            field=models.ForeignKey(blank=True, help_text='Deprecated for new institutional entries. Link a confirmed contribution; historical data are retained internally.', null=True, on_delete=django.db.models.deletion.PROTECT, to='people.facultycontribution'),
        ),
        migrations.AddField(
            model_name='facultyextensionproject',
            name='reconciled_contribution',
            field=models.ForeignKey(blank=True, help_text='Deprecated for new institutional entries. Link a confirmed contribution; historical data are retained internally.', null=True, on_delete=django.db.models.deletion.PROTECT, to='people.facultycontribution'),
        ),
        migrations.AddField(
            model_name='facultypublication',
            name='reconciled_contribution',
            field=models.ForeignKey(blank=True, help_text='Deprecated for new institutional entries. Link a confirmed contribution; historical data are retained internally.', null=True, on_delete=django.db.models.deletion.PROTECT, to='people.facultycontribution'),
        ),
        migrations.AddField(
            model_name='facultyresearchproject',
            name='reconciled_contribution',
            field=models.ForeignKey(blank=True, help_text='Deprecated for new institutional entries. Link a confirmed contribution; historical data are retained internally.', null=True, on_delete=django.db.models.deletion.PROTECT, to='people.facultycontribution'),
        ),
        migrations.AlterField(
            model_name='facultycontribution',
            name='role',
            field=models.CharField(blank=True, help_text='Use only a role established by the source; conference author does not mean presenter.', max_length=100),
        ),
    ]
