# Generated by Django 6.0.8 on 2026-10-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_reconcile_historical_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('chairperson', 'Department chairperson'), ('admin_aide', 'Department administrative aide'), ('lab_technician', 'Laboratory technician')], max_length=32)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_role', to='people.facultymember')),
            ],
            options={
                'ordering': ['sort_order', 'person__title'],
            },
        ),
    ]
