# Generated by Django 6.0.9 on 2026-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_concise_ongoing_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyeducation',
            name='academic_status',
            field=models.CharField(choices=[('review', 'Internal review'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('experience', 'Academic experience')], default='review', max_length=16),
        ),
        migrations.AddField(
            model_name='facultyeducation',
            name='verification_reference',
            field=models.TextField(blank=True, help_text='Internal source/approval reference supporting the academic status and public wording.'),
        ),
        migrations.AlterField(
            model_name='facultyeducation',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facultyeducation',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal editorial notes; never exposed by the public API.'),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='profile_summary',
            field=models.TextField(blank=True, help_text='Optional approved biography. Leave blank when unavailable; do not repeat rank or expertise fields.'),
        ),
    ]
