# Generated by Django 6.0.3 on 2026-03-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_updated_note', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('ANNOUNCEMENT', 'Announcement'), ('EVENT', 'Event')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_documents', models.ManyToManyField(blank=True, related_name='news_posts', to='quality.evidencedocument')),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
    ]
